memoria1: memoria1.cpp
	g++ memoria1.cpp -o memoria1

memoria2: memoria2.cpp
	g++ memoria2.cpp -o memoria2

memoria2c: memoria2c.cpp
	g++ memoria2c.cpp -o memoria2c

memoria2d: memoria2d.cpp
	g++ memoria2d.cpp -o memoria2d

memoria3: memoria3.cpp
	g++ memoria3.cpp -o memoria3

memoria4: memoria4.cpp
	g++ memoria4.cpp -o memoria4

memoria5: memoria5.cpp
	g++ memoria5.cpp -o memoria5

memoria6: memoria6.cpp
	g++ memoria6.cpp -o memoria6

memoria6b: memoria6b.cpp
	g++ memoria6b.cpp -o memoria6b

memoria7: memoria7.cpp
	g++ memoria7.cpp -o memoria7

memoria8: memoria8.cpp
	g++ memoria8.cpp -o memoria8

memoria9: memoria9.cpp
	g++ memoria9.cpp -o memoria9

memoria10: memoria10.cpp
	g++ memoria10.cpp -o memoria10

memoria11: memoria11.cpp
	g++ memoria11.cpp -o memoria11

clean:
	rm *.exe